lab02/calculadora/urls.py
from django.urls import path
from . import views


app_name = "calculadora"

urlpatterns = [
    path('', views.index, name="index"),
    path('send/', views.send, name="send")
]

lab02/encuesta/urls.py
from django.urls import path
from . import views


app_name = "encuesta"

urlpatterns = [
    path('', views.index, name="index"),
    path('enviar', views.enviar, name="enviar")
]

lab02/lab02/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('encuesta/', include('encuesta.urls')),
    path('calculadora/', include('calculadora.urls')),
    path('volumen/',include('volumen.urls')),
]

lab02/volumen/urls.py
from django.urls import path
from . import views

app_name = "volumen"

urlpatterns = [
    path('', views.index, name="index"),
    path('send/', views.send, name="send")
]

lab02/calculadora/models.py
from django.db import models

# Create your models here.

lab02/encuesta/models.py
from django.db import models

# Create your models here.

lab02/volumen/models.py
from django.db import models

# Create your models here.

lab02/calculadora/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'calculadora/form.html',{"tittle":"Calculator"})

def send(request):
    result = 0
    number1 = int(request.POST['number1'])
    number2 = int(request.POST['number2'])
    
    if(request.POST['operation'] == 'suma'):
        result = number1 + number2      
    elif request.POST['operation'] == 'resta':
        result = number1 - number2
    elif request.POST['operation'] == 'multiplicacion':
        result = number1 * number2
    elif request.POST['operation'] == 'division':
        result = number1 / number2

    return render(request, 'calculadora/result.html', {
        "number1" : request.POST['number1'],
        "number2" : request.POST['number2'],
        "operation" : request.POST['operation'],
        "result" : result,
        "tittle" : "Result",
    })

lab02/encuesta/views.py
from django.shortcuts import render

def index(request):
    context = {
        "titulo":"Formulario",
    }
    return render(request, "encuesta/formulario.html",context)


def enviar(request):
    context = {
        "titulo":"Respuesta",
        "nombre":request.POST['nombre'],
        "clave":request.POST['password'],
        "educacion":request.POST['educacion'],
        "nacionalidad":request.POST['nacionalidad'],
        "idiomas":request.POST.getlist('idiomas'),
        "correo":request.POST['email'],
        "website":request.POST['sitioweb']
    }
    return render(request, 'encuesta/respuesta.html',context)

lab02/volumen/views.py
from django.shortcuts import render
import math

def index(request):
    return render(request, 'volumen/form.html',{
        "tittle" : "Calculo del volumen de un cilindro "
    })

def send(request):
    try:
        radio = float(request.POST['diametro']) / 2
        altura = float(request.POST['altura'])

        volumen = math.pow(radio, 2) * math.pi * altura

        return render(request, 'volumen/result.html', {
            "title": "Volumen del cilindro",
            "volumen": volumen
        })
    except ValueError:
        return render(request, 'volumen/form.html', {
            "error_message": "Asegúrate de que los valores proporcionados sean números válidos."
        })

lab02/calculadora/templates/calculadora/form.html
<h2>{{ tittle }}</h2>
<form action="{% url 'calculadora:send' %}" method="post">
    {% csrf_token %}
    <label for="">Number 1</label>
    <input type="number" name="number1">

    <label for="">Number 2</label>
    <input type="number" name="number2">

    <Label>Operacion</Label>
    <select name="operation">
        <option value="suma">Suma</option>
        <option value="resta">Resta</option>
        <option value="multiplicacion">Multiplicacion</option>
        <option value="division">Division</option>
    </select>

    <input type="submit" value="Send">
</form>

lab02/calculadora/templates/calculadora/result.html
<h2>{{ tittle }}</h2>

<p>La {{operation}} de {{number1}} y {{number2}} es {{result}}</p>

lab02/encuesta/templates/encuesta/formulario.html
<h2>{{ titulo }}</h2>
<form action="{% url 'encuesta:enviar' %}", method="post">
    {% csrf_token %}
    Nombre:
    <input type="text" name="nombre" maxlength="50"><br>
    Contraseña:
    <input type="password" name="password"><br>
    Education:
    <select name="educacion">
        <option value="sin-estudios">Sin estudios</option>
        <option value="eduacion-obligatoria">Educacion Obligatoria</option>
        <option value="formacion-profesional">Formacion Profesional</option>
        <option value="universidad">Universidad</option>
    </select>
    Nacionalidad:
    <input type="radio" name="nacionalidad" value="hispana">Hispana</input>
    <input type="radio" name="nacionalidad" value="otra">Otra</input><br>
    Idiomas:
    <input type="checkbox" name="idiomas" value="español" checked="checked">Español</input>
    <input type="checkbox" name="idiomas" value="ingles">Ingles</input>
    <input type="checkbox" name="idiomas" value="frances">Frances</input>
    <input type="checkbox" name="idiomas" value="aleman">Aleman</input>
    Email:
    <input type="text" name="email"><br>
    Sitio Web:
    <input type="text" name="sitioweb"><br>
    <input type="submit" name>
</form> 

lab02/encuesta/templates/encuesta/respuesta.html
<h2>{{ titulo }}</h2>
<p>Nombre: {{ nombre }}</p>
<p>Clave: {{ clave }}</p>
<p>Educacion: {{ educacion }}</p>
<p>Nacionalidad: {{ nacionalidad }}</p>
<p>Idiomas:</p>
<ul>
    {% for item in idiomas %}
    <li>{{ item }}</li>
    {% endfor %}
</ul>
<p>Email: {{ correo }}</p>
<p>Sitio Web: {{ website }}</p>

lab02/volumen/templates/volumen/form.html
<h2>{{ tittle }}</h2>
<form action="{% url 'volumen:send' %}" method="post">
    {% csrf_token %}

    {% if error_message %}
    <p style="color: red;">{{ error_message }}</p>
    {% endif %}

    <label for="diametro">Diámetro</label>
    <input type="text" name="diametro">

    <label for="altura">Altura</label>
    <input type="text" name="altura">

    <input type="submit" value="Enviar">
</form>

lab02/volumen/templates/volumen/result.html
<h2>{{ tittle }}</h2>
<p>El volumen del cilindro es de {{ volumen }} metros cubicos</p>